// The DMP outline (spec "Outline"): each spec file and its numbered headings,
// in order. Numbers never change within a major version; titles may.
export const OUTLINE: readonly {
  file: string;
  headings: readonly string[];
}[] = [
  {
    file: '00-front-matter.md',
    headings: [
      '# 0 Front matter',
      '## 0.1 Abstract',
      '## 0.2 Status of this document',
      '## 0.3 Changes since the last draft',
    ],
  },
  {
    file: '01-introduction.md',
    headings: [
      '# 1 Introduction',
      '## 1.1 Goals',
      '## 1.2 Non-goals',
      '## 1.3 Relation to A2A, MCP and federation',
      '## 1.4 Conventions',
    ],
  },
  {
    file: '02-terminology.md',
    headings: [
      '# 2 Terminology',
      '## 2.1 Hosts and principals',
      '## 2.2 Work items and sessions',
      '## 2.3 Deciding principals and the system address',
      '## 2.4 Mailboxes and deliveries',
      '## 2.5 Gates, gate data and markers',
    ],
  },
  {
    file: '03-addresses.md',
    headings: [
      '# 3 Addresses',
      '## 3.1 Grammar',
      '## 3.2 Limits',
      '## 3.3 Reserved characters',
      '## 3.4 Schemes',
      '## 3.5 Resolution',
      '## 3.6 Implicit members',
      '## 3.7 De-duplication',
    ],
  },
  {
    file: '04-messages.md',
    headings: [
      '# 4 Messages',
      '## 4.1 Envelope',
      '## 4.2 Kinds and private use',
      '## 4.3 Refs',
      '## 4.4 Refs received from other hosts',
      '## 4.5 Validation and limits',
      '## 4.6 Threads and participation',
      '## 4.7 Questions, answers and handoffs',
      '## 4.8 Close',
      '## 4.9 Idempotency and replay',
    ],
  },
  {
    file: '05-gates.md',
    headings: [
      '# 5 Gates',
      '## 5.1 Gate data',
      '## 5.2 Deciding principals',
      '## 5.3 Raising a gate',
      '## 5.4 Answering a gate',
      '## 5.5 Effects',
      '## 5.6 Unknown types fail closed',
      '## 5.7 Ignored answers',
      '## 5.8 Locality',
      '## 5.9 The wake gate',
    ],
  },
  {
    file: '06-delivery.md',
    headings: [
      '# 6 Delivery',
      '## 6.1 States',
      '## 6.2 Mode selection',
      '## 6.3 Outbox and recovery',
      '## 6.4 Session start',
      '## 6.5 Wake policy',
      '## 6.6 Guardrails',
      '## 6.7 Muted senders',
      '## 6.8 Presenting messages to models',
    ],
  },
  {
    file: '07-mailboxes-and-channels.md',
    headings: [
      '# 7 Mailboxes and channels',
      '## 7.1 Mailboxes',
      '## 7.2 Channels',
      '## 7.3 Membership',
    ],
  },
  {
    file: '08-a2a-binding.md',
    headings: [
      '# 8 A2A binding',
      '## 8.1 Agent and skills',
      '## 8.2 Mapping',
      '## 8.3 Extension activation and placement',
      '## 8.4 envelope/v1',
      '## 8.5 gate/v1',
      '## 8.6 work/v1',
      '## 8.7 Task-state projection',
      '## 8.8 External senders',
      '## 8.9 Outbound peers',
      '## 8.10 Declared deviations',
    ],
  },
  {
    file: '09-identity-and-authorization.md',
    headings: [
      '# 9 Identity and authorization',
      '## 9.1 Principals',
      '## 9.2 Deciding principals',
      '## 9.3 Reads',
    ],
  },
  {
    file: '10-errors.md',
    headings: [
      '# 10 Errors',
      '## 10.1 Codes',
      '## 10.2 Fields',
      '## 10.3 Unknown codes',
    ],
  },
  {
    file: '11-registries.md',
    headings: [
      '# 11 Registries',
      '## 11.1 Address schemes',
      '## 11.2 Address characters',
      '## 11.3 Envelope fields',
      '## 11.4 Kinds',
      '## 11.5 Ref types',
      '## 11.6 Gate types',
      '## 11.7 System markers',
      '## 11.8 Delivery states',
      '## 11.9 Error codes',
      '## 11.10 Extension URIs',
      '## 11.11 Registration policy',
    ],
  },
  {
    file: '12-conformance.md',
    headings: [
      '# 12 Conformance',
      '## 12.1 Claims',
      '## 12.2 Levels',
      '## 12.3 Profiles',
      '## 12.4 The kit',
      '## 12.5 Requirements the kit does not test',
      '## 12.6 Declared deviations',
      '## 12.7 Claim wording',
    ],
  },
  {
    file: '13-security-and-privacy.md',
    headings: [
      '# 13 Security and privacy considerations',
      '## 13.1 The system address',
      '## 13.2 Deciding principals',
      '## 13.3 Raise and answer authority',
      '## 13.4 Effects need a deciding answer',
      '## 13.5 Non-participants learn nothing',
      '## 13.6 Reads',
      '## 13.7 Identifier entropy',
      '## 13.8 Retention and deletion',
      '## 13.9 Egress through bindings',
      '## 13.10 Logging',
      '## 13.11 Gate payloads as references',
      '## 13.12 Injection-safe presentation',
      '## 13.13 Size limits',
      '## 13.14 System markers',
      '## 13.15 Idempotency scope',
      '## 13.16 Local identity',
    ],
  },
  {
    file: '14-versioning.md',
    headings: [
      '# 14 Versioning, change process and security process',
      '## 14.1 Document versions',
      '## 14.2 Change process',
      '## 14.3 Security process',
      '## 14.4 Extension versions',
      '## 14.5 Package versions',
    ],
  },
  {
    file: 'appendix-a-daemon-api.md',
    headings: [
      '# Appendix A Dispatch daemon HTTP and WebSocket API',
      '## A.1 Authentication and tiers',
      '## A.2 Routes',
      '## A.3 Events',
    ],
  },
  {
    file: 'appendix-b-agent-tools.md',
    headings: [
      '# Appendix B Agent tools',
      '## B.1 Tools',
      '## B.2 Blocking waits',
      '## B.3 Memory tools',
    ],
  },
  {
    file: 'appendix-c-dispatch-profile.md',
    headings: [
      '# Appendix C Dispatch profile',
      '## C.1 Identifiers',
      '## C.2 System address and owner',
      '## C.3 Gate types',
      '## C.4 Markers',
      '## C.5 Retention',
      '## C.6 Presentation',
      '## C.7 Guardrail defaults',
      '## C.8 Wake policy',
    ],
  },
  {
    file: 'appendix-d-json-schemas.md',
    headings: [
      '# Appendix D JSON Schemas',
      '## D.1 Schemas',
      '## D.2 Adapter messages',
    ],
  },
  {
    file: 'appendix-e-examples.md',
    headings: ['# Appendix E Examples', '## E.1 Examples'],
  },
  {
    file: 'appendix-f-federation.md',
    headings: [
      '# Appendix F Federation wire and receive',
      '## F.1 FederatedOp',
      '## F.2 Canonical JSON and domain tags',
      '## F.3 Sealing',
      '## F.4 Mail and state payloads',
      '## F.5 Receive',
      '## F.6 Settlement',
      '## F.7 Team memory and doc ops',
    ],
  },
];
